name: shosu
description: 推理文字冒险游戏《魔法少女ノ魔女裁判》的二次创作的移动应用
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  audioplayers: ^6.1.0
  vibration: ^2.0.0
  shared_preferences: ^2.3.3
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
  
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
